# Generated by Django 3.1.2 on 2020-10-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('father_name', models.CharField(max_length=32)),
                ('email_id', models.CharField(max_length=32)),
                ('phone_no', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
